#
# Copyright (c) Peter de Vocht, 2016
#
# All rights reserved. No part of this publication may be reproduced, distributed, or
# transmitted in any form or by any means, including photocopying, recording, or other
# electronic or mechanical methods, without the prior written permission of the publisher,
# except in the case of brief quotations embodied in critical reviews and certain other
# noncommercial uses permitted by copyright law.
#

#
# external data files;  Spacy and Neural Nets
#
  - name: download Spacy files
    shell: python -m spacy download en_core_web_sm

# copy spacy parser server files

  - name: copying spacy server
    copy: src={{ dev_base }}/spacy_parser/ dest={{ kai_base }}/spacy_parser/ force=yes

  - name: set exec permissions on spacy script
    file: path={{ kai_base }}/spacy_parser/start.sh owner=kai group=kai mode=a+x

  - name: set exec permissions on spacy python
    file: path={{ kai_base }}/spacy_parser/server.py owner=kai group=kai mode=a+x

